# Generated by Django 3.2.4 on 2021-06-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название поста')),
                ('text', models.TextField(db_index=True, verbose_name='Текст поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления поста')),
                ('rubric', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Тема поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.profile')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления комментария')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_user.profile')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created'],
            },
        ),
    ]
