# Generated by Django 3.2.4 on 2021-06-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='фамилия')),
                ('subscriptions', models.TextField(blank=True, verbose_name='подписки')),
                ('my_subscribers', models.TextField(blank=True, verbose_name='мои подписчики')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
