# Generated by Django 3.2.4 on 2021-06-14 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.'))], verbose_name='логин')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта (mail)')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('img_profile', models.ImageField(blank=True, upload_to='profile_images/', verbose_name='фото')),
                ('subscriptions', models.ManyToManyField(blank=True, to='profile_user.Profile', verbose_name='Подписки/подписчики')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
