# Generated by Django 3.2.4 on 2021-06-18 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_auto_20210618_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefollowing',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
